global:
  scrape_interval: 15s  # интервал сбора метрик

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'django-app'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['app:8080']  # приложение Django

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']