# Generated by Django 5.2 on 2025-04-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='hunger',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='energy',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('playful', 'Playful'), ('sleepy', 'Sleepy')], default='happy', max_length=20),
        ),
    ]
