# Generated by Django 5.2 on 2025-04-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.CharField(choices=[('pet_images/cat1.png', 'Cat 1'), ('pet_images/cat2.jpg', 'Cat 2')], max_length=255),
        ),
    ]
