# Generated by Django 5.2 on 2025-04-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_alter_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
