# Generated by Django 5.2 on 2025-04-14 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_alter_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
