# Generated by Django 5.2 on 2025-04-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_pet_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='hunger',
            new_name='satiety',
        ),
    ]
