# Generated by Django 5.2 on 2025-04-14 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_rename_hunger_pet_satiety'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='pet.pet')),
            ],
        ),
    ]
