# Generated by Django 5.2 on 2025-05-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqrs_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.IntegerField(unique=True)),
                ('current_energy', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='EntityHistory',
        ),
        migrations.DeleteModel(
            name='EntityView',
        ),
        migrations.DeleteModel(
            name='EventStore',
        ),
    ]
